# file: postgresql/tasks/extensions/dev_headers.yml

- name: PostgreSQL | Extensions | Make sure the development headers are installed (apt)
  apt:
    name: libpq-dev
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  notify:
    - restart postgresql
  when: ansible_pkg_mgr == "apt"

- name: PostgreSQL | Extensions | Make sure the development headers are installed (yum)
  yum:
    name: "postgresql{{ postgresql_version_terse }}-devel"
    state: present
  environment: "{{postgresql_env}}"
  when: ansible_pkg_mgr == "yum"
