---
- name: Ensure dist folder exists
  file:
    state: directory
    path: "{{ item }}"
    mode: "u=rwx,g=rwx,o=rwx"
  with_items:
    - /opt/dist
    - /opt/dist/yum
    - /opt/dist/pypi

- include: repos/centos.yml
  when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7"

- include: repos/redhat.yml
  when: "ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 7"
