---
- name: Ensure dist folder exists
  file:
    state: directory
    path: "/opt/dist"
    mode: "u=rwx,g=rwx,o=rwx"

- include: repos/centos.yml
  when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7"

- include: repos/redhat.yml
  when: "ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 7"
