---
- name: Ensure dist folder exists
  file:
    state: directory
    path: "{{ item }}"
    mode: "u=rwx,g=rwx,o=rwx"
  with_items:
    - /opt/dist
    - /opt/dist/yum
    - /opt/dist/pypi
    - /opt/dist/tars
    - /opt/dist/git
    - /opt/dist/jpi

- include: repos/destroy_old_repos.yml
  when: "{{ destroy_existing_repos }} or {{ distribute_dependencies }}"

- include: repos/centos.yml
  when: "ansible_distribution == 'CentOS' and ansible_distribution_major_version|int == 7 and not distribute_dependencies"

- include: repos/redhat.yml
  when: "ansible_distribution == 'RedHat' and ansible_distribution_major_version|int == 7 and not distribute_dependencies"

- name: Hack other modules so they don't do yum things
  include: repos/hacks.yml

- include: repos/local.yml
  when: "{{ distribute_dependencies }}"

- name: Distribute dependencies
  include: packages/distribute.yml
  when: "{{ distribute_dependencies }}"

- name: Package dependencies
  include: packages/package.yml
  when: "{{ package_dependencies }}"

- name: Collect dependencies
  include: packages/collect.yml
  when: "{{ collect_dependencies }}"
