# (c) Crown Owned Copyright, 2016. Dstl.
---
- name: create jobs from templates
  template:
    dest: "{{ jenkins_job_builder_file_jobs_dest }}/{{ item }}"
    src: "jobs/{{ item }}.j2"
  with_items:
    - "update-jenkins.yml"
    - "lighthouse.yml"
- name: "Force jobs to reload"
  command: /bin/true
  notify:
    - Check jenkins
    - Reload jenkins-jobs
