galaxy_info:
  author: Michael Allen
  description: Python role for running Lighthouse apps
  company: Digi2al

  license: MIT

  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags: []

dependencies:
  - { role: octarine.postgresql }
  - { role: AerisCloud.repos }
