---
- name: Force PostgreSQL to not install it's repo
  set_fact:
    postgresql_manage_repository: no
  when: "{{ distribute_dependencies }} or {{ destroy_existing_repos }}"

- name: Force jenkins to install from /opt/dist
  set_fact:
    jenkins_manage_repository: no
  when: "{{ distribute_dependencies }} or {{ destroy_existing_repos }}"

- name: Force phantomjs to download to /opt/dist
  set_fact:
    phantomjs_download_location: /opt/dist/tars

- name: Force ansible pip commands to use /opt/dist
  set_fact:
    pip_extra_args: '--find-links="{{ remote_repo_location }}/pypi" --no-index'
  when: "{{ distribute_dependencies }}"
