# (c) Crown Owned Copyright, 2016. Dstl.
---
- name: 'Create local repo'
  template:
    src: "local.repo.j2"
    dest: "/etc/yum.repos.d/local.repo"
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'
