# (c) Crown Owned Copyright, 2016. Dstl.
galaxy_info:
  author: Dan Hough
  description: Installs phantomjs
  company: Digi2al

  license: MIT

  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags: []

dependencies: []
