---
- name: Rsync dependencies from remote server
  synchronize:
    src: "{{ remote_repo_location }}/"
    dest: "{{ local_repo_location }}/"
    rsync_opts:
      - "--omit-dir-times"
    mode: pull
