---
- name: Install packages used in packaging
  yum:
    name: "{{ item }}"
  with_items:
    - yum-utils
    - createrepo

- name: Collect installed package names
  shell: 'rpm -qa --queryformat "%{name}\n" | sort | grep --invert-match "gpg-pubkey" > {{ remote_repo_location }}/pkg_list'

- name: Download all installed RPMs
  shell: "yumdownloader --destdir {{ remote_repo_location }}/yum $(<{{ remote_repo_location }}/pkg_list)"

- name: Create a yum repo
  shell: "createrepo {{ remote_repo_location }}/yum"
  when: "{{ create_repo_during_package }}"
