# (c) Crown Owned Copyright, 2016. Dstl.
---
- name: Ensure any existing packages are owned by ansible user
  file:
    path: "/opt/dist"
    recurse: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes

- name: Install packages used in packaging
  yum:
    name: "{{ item }}"
  with_items:
    - yum-utils
    - createrepo

- name: Collect installed package names
  shell: 'rpm -qa --queryformat "%{name}-%{version}\n" | sort | grep --invert-match "gpg-pubkey" > {{ remote_repo_location }}/pkg_list'

- name: Download all installed RPMs
  shell: "yumdownloader --destdir {{ remote_repo_location }}/yum $(<{{ remote_repo_location }}/pkg_list)"
  become: yes

- name: Ensure ansible installed pips are packaged
  shell: 'pip3.5 download --dest "{{ remote_repo_location }}/pypi" {{ item }}'
  with_items:
    - uwsgi
    - virtualenv
    - pip
  when: "{{ package_dependencies }}"

- name: Ensure ansible installed pips are packaged
  shell: 'pip2.7 download --dest "{{ remote_repo_location }}/pypi" {{ item }}'
  with_items:
    - jenkins-job-builder
    - pbr
    - pip
    - ansible
  when: "{{ package_dependencies }}"

- name: Clone lighthouse git repo
  git:
    repo: "{{ lighthouse_repo }}"
    version: "{{ lighthouse_version }}"
    dest: "/opt/dist/git/lighthouse"
    accept_hostkey: True
    key_file: "/var/lib/jenkins/.ssh/github_rsa"
    force: yes
    bare: yes
  when: "{{ package_lighthouse_repo }}"

- name: Clone builder git repo
  git:
    repo: "{{ builder_repo }}"
    version: "{{ builder_version }}"
    dest: "/opt/dist/git/lighthouse-builder"
    accept_hostkey: True
    key_file: "/var/lib/jenkins/.ssh/github_rsa"
    force: yes
    bare: yes
  when: "{{ package_builder_repo }}"

- name: Clone lighthouse git repo in to workspaces
  git:
    repo: "{{ lighthouse_repo }}"
    version: "{{ lighthouse_version }}"
    dest: "{{ item }}"
    accept_hostkey: True
    key_file: "/var/lib/jenkins/.ssh/github_rsa"
    force: yes
  with_items:
    - /opt/dist/workspaces/lighthouse-build-pullrequests
    - /opt/dist/workspaces/lighthouse-build
    - /opt/dist/workspaces/lighthouse-acceptance-test
  when: "{{ package_lighthouse_repo }}"

- name: Clone builder git repo in to workspaces
  git:
    repo: "{{ builder_repo }}"
    version: "{{ builder_version }}"
    dest: "{{ item }}"
    accept_hostkey: True
    key_file: "/var/lib/jenkins/.ssh/github_rsa"
    force: yes
  with_items:
    - /opt/dist/workspaces/lighthouse-deploy
    - /opt/dist/workspaces/update-jenkins
    - /opt/dist/workspaces/package-dependencies
  when: "{{ package_builder_repo }}"

- name: Clone bootstrap git repo
  git:
    repo: "{{ builder_repo }}"
    version: "{{ builder_version }}"
    dest: "/opt/dist/bootstrap"
    accept_hostkey: True
    key_file: "/var/lib/jenkins/.ssh/github_rsa"
    force: yes
  when: "{{ package_builder_repo }}"

- name: Package jenkins plugins
  get_url:
    url: "https://updates.jenkins-ci.org/latest/{{ item }}.hpi"
    dest: "/opt/dist/jpi/{{ item }}.hpi"
  with_items: "{{ jenkins_plugins }}"
  when: "{{ package_jenkins_plugins }}"

- name: Ensure packages are owned by ansible user
  file:
    path: "/opt/dist"
    recurse: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create a yum repo
  shell: "createrepo {{ remote_repo_location }}/yum"
  when: "{{ create_repo_during_package }}"
