---
- name: Install packages used in packaging
  yum:
    name: "{{ item }}"
  with_items:
    - yum-utils
    - createrepo

- name: Collect installed package names
  shell: 'rpm -qa --queryformat "%{name}\n" | sort | grep --invert-match "gpg-pubkey" > {{ remote_repo_location }}/pkg_list'

- name: Download all installed RPMs
  shell: "yumdownloader --destdir {{ remote_repo_location }}/yum $(<{{ remote_repo_location }}/pkg_list)"

- name: Create a yum repo
  shell: "createrepo {{ remote_repo_location }}/yum"
  when: "{{ create_repo_during_package }}"

- name: Ensure ansible installed pips are packaged
  shell: 'pip3.5 download --dest "{{ remote_repo_location }}/pypi" {{ item }}'
  with_items:
    - uwsgi
    - virtualenv

- name: Package git repos
  shell: "cp -r {{ item.src }} /opt/dist/git/{{ item.name }}"
  args:
    creates: "/opt/dist/git/{{ item.name }}"
  with_items: "{{ dependencies_git_repos }}"
