---
builder_repo: git@github.com:dstl/lighthouse-builder.git
builder_version: origin/master

jenkins_user: jenkins
jenkins_plugins:
  - scm-api
  - git-client
  - jquery
  - token-macro
  - plain-credentials
  - github-api
  - git
  - sonar
  - ssh
  - build-monitor-plugin
  - ansicolor
  - github

git_packages:
  - git2u

jenkins_job_builder_config_jenkins_url: http://localhost:8080
jenkins_job_builder_file_jobs_src: ''
jenkins_job_builder_user_name: '{{ jenkins_user }}'
jenkins_job_builder_user_group: '{{ jenkins_user }}'
jenkins_job_builder_file_jobs_group: '{{ jenkins_user }}'
jenkins_job_builder_file_jobs_owner: '{{ jenkins_user }}'
jenkins_job_builder_install_method: 'pip'

jenkins_pypi_dist_location: '/opt/dist/pypi'

postgresql_databases:
  - name: lighthouse
    owner: '{{ jenkins_user }}'

postgresql_users:
  - name: '{{ jenkins_user }}'
    pass: '{{ jenkins_user }}'
    encrypted: no
  - name: lighthouse

postgresql_user_privileges:
  - name: lighthouse
    db: lighthouse
    priv: "ALL"
    role_attr_flags: "CREATEDB"
  - name: '{{ jenkins_user }}'
    db: lighthouse
    priv: "ALL"
    role_attr_flags: "CREATEDB"
