# (c) Crown Owned Copyright, 2016. Dstl.
---
- name: restart emperor
  service:
    name: emperor
    state: restarted
    enabled: yes
- name: reload systemd
  shell: systemctl daemon-reload
  sudo: true
- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
