Vagrant.require_version ">= 1.6.0"

VAGRANTFILE_API_VERSION = "2"

# Require YAML module
require 'yaml'

# Read YAML file with box details
servers = YAML.load_file('servers.yml')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  servers.each do |servers|
    config.vm.define servers["name"] do |srv|
      srv.vm.box = servers["box"]
      srv.vm.network "private_network", ip: servers["ip"]
      srv.vm.provider "virtualbox" do |vb|
        vb.memory = servers["ram"]
      end
      srv.vm.provider "vmware_fusion" do |vf|
        vf.vmx["vhv.enable"] = "TRUE"
        vf.vmx["allowNested"] = "TRUE"
      end
      srv.vm.provision "file", source: "bootstrap.yml", destination: "bootstrap.yml"
      srv.vm.provision "shell", path: "bootstrap.sh"
    end
  end
end
