# (c) Crown Owned Copyright, 2016. Dstl.
---
# tasks file for python
- name: install python software
  yum: pkg={{item}} state=installed
  with_items:
    - gcc
    - gcc-c++
    - python-pip
    - python35u-pip
    - python35u-devel
- name: Update pip
  pip:
    name: pip
    executable: "{{ item }}"
    state: latest
    extra_args: "{{ pip_extra_args }}"
  with_items:
    - pip3.5
    - pip2.7
- name: install system pip packages
  pip:
    name: "{{item}}"
    executable: pip3.5
    extra_args: "{{ pip_extra_args }}"
  with_items:
    - virtualenv
    - uwsgi
- include: uwsgi.yml
- include: nginx.yml
- name: Disable SELinux
  selinux:
    state: disabled
