# (c) Crown Owned Copyright, 2016. Dstl.
- hosts: jenkins
  sudo: true
  vars_files:
    - vars/jenkins.yml
    - "{{ secrets_vars }}"
    - ../secrets/all.secrets.yml
  roles:
    - digi2al.dependencies
    - digi2al.migration
    - geerlingguy.jenkins
    - openstack.jenkins-job-builder
    - octarine.postgresql
    - digi2al.python
    - digi2al.jenkins
    - digi2al.phantomjs
    - digi2al.dependencies
- hosts: development
  sudo: true
  vars_files:
    - vars/lighthouse.yml
    - "{{ secrets_vars }}"
  roles:
    - digi2al.dependencies
    - digi2al.python
    - bennojoy.openldap_server
    - digi2al.phantomjs
- hosts: lighthouse-app-server
  sudo: true
  vars_files:
    - vars/lighthouse.yml
    - "{{ secrets_vars }}"
    - ../secrets/all.secrets.yml
  roles:
    - digi2al.dependencies
    - digi2al.migration
    - digi2al.python
    - dstl.lighthouse

- hosts: package-lighthouse
  vars_files:
    - vars/package_lighthouse.yml
    - "{{ secrets_vars }}"
    - ../secrets/all.secrets.yml
  roles:
    - digi2al.dependencies
- hosts: package-dependencies
  sudo: true
  vars_files:
    - vars/jenkins.yml
    - vars/package_dependencies.yml
    - "{{ secrets_vars }}"
    - ../secrets/all.secrets.yml
  roles:
    - digi2al.dependencies
