# -*- mode: ruby -*-
# vi: set ft=ruby :
# (c) Crown Owned Copyright, 2016. Dstl.

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Require YAML module
require 'yaml'

# Read YAML file with box details
servers = YAML.load_file('servers.yml')

groups = {}
servers.each do |server|
  server['groups'].each do |group|
    groups[group] ||= []
    groups[group].push(server['name'])
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  servers.each do |server|
    config.vm.define server["name"] do |srv|
      srv.vm.box = server["box"]
      srv.vm.network "private_network", ip: server["ip"]
      srv.vm.hostname = server["host"]

      server["mounts"].each do |mount|
        path = ENV[mount["envvar"]]
        if path
          srv.vm.synced_folder path, mount["target"], type: 'nfs',
            mount_options: ['rsize=8192', 'wsize=8192']
        else
          puts "#{mount["envvar"]} not set"
          puts "To share the app into the VM set it in your ~/.bashrc"
          puts "export #{mount["envvar"]}=~/Projects/dtsl-lighthouse"
        end
      end

      if Vagrant.has_plugin?("vagrant-cachier")
        srv.cache.scope = :machine
      end
      srv.vm.provider "virtualbox" do |vb|
        vb.memory = server["ram"]
      end
      srv.vm.provider "vmware_fusion" do |vf|
        vf.vmx["vhv.enable"] = "TRUE"
        vf.vmx["allowNested"] = "TRUE"
      end
      srv.vm.synced_folder "../.", "/vagrant"
      srv.vm.provision "ansible" do |ansible|
        ansible.playbook = server["playbook"]
        ansible.groups = groups
      end
    end
  end
end
